const seoKeywords = {
  primaryKeywords: [
    "Tshwane Varsity Hackathon",
    "University hackathon",
    "Tshwane University hackathon",
    "Student innovation competition",
    "Tech hackathon South Africa",
    "Coding competition",
    "Student tech event",
    "Hackathon for students",
    "TVH hackathon",
    "ICEP hackathon",
    "Innovation challenge",
  ],
  longTailKeywords: [
    "How to join Tshwane University hackathon",
    "Benefits of participating in a student hackathon",
    "Tshwane Varsity Hackathon registration process",
    "Student coding competition Pretoria",
    "Tech event for university students South Africa",
    "Win prizes at a hackathon",
    "Hackathon deadlines and requirements",
    "Best student hackathons in South Africa",
    "ICEP tech innovation challenge",
    "TVH hackathon past winners",
  ],
  relatedTerms: [
    "Student coding bootcamp",
    "University tech symposium",
    "Learn coding through hackathons",
    "Team-based innovation challenge",
    "Software development competition",
    "STEM events for students",
    "Networking for tech students",
    "Pitch your tech idea",
    "Hackathon mentorship programs",
    "Tech workshops for students",
  ],
  locationBasedKeywords: [
    "Hackathon in Pretoria",
    "Tshwane tech events",
    "South Africa student competitions",
    "Gauteng coding hackathon",
    "University events Pretoria",
    "ICEP South Africa hackathon",
    "Local tech innovation Pretoria",
    "TVH hackathon Gauteng",
  ],
  audienceSpecificKeywords: [
    "Hackathons for university students",
    "Computer science student competitions",
    "Engineering student challenges",
    "Young innovators South Africa",
    "Tech-savvy students events",
    "Future developers hackathon",
    "Student entrepreneurship programs",
    "Women in tech hackathons",
  ],
  actionKeywords: [
    "Register for TVH hackathon",
    "Apply for student hackathon",
    "Compete in coding challenge",
    "Submit hackathon project",
    "Win tech prizes",
    "Join innovation competition",
    "Volunteer at hackathon",
    "Sponsor student tech event",
  ],
};

export default seoKeywords;
