import { assets } from "./assets";

export interface TeamMember {
  id: string;
  name: string;
  title: string;
  department: string;
  image: string;
  bio: string[];
  email?: string;
  linkedin?: string;
  twitter?: string;
  website?: string;
  location?: string;
  skills?: string[];
}

// Helper function to generate placeholder image URLs with specific dimensions
function getPlaceholderImage(name: string): string {
  return `/placeholder.svg?height=400&width=400&text=${encodeURIComponent(
    name.replace(" ", "+")
  )}`;
}

export const teamData: TeamMember[] = [
  // Leadership Team
  {
    id: "member-1",
    name: "Morongoe Mashoeng",
    title: "1st Vice Chief Organizer",
    department: "Executive Organizing Team",
    image: "/assets/img/team/mrg.webp",
    bio: [
      "My name is Morongoe Mashoeng. I am the Acting Innovation Consultant in the City of Tshwane. In my 10 years in local government, I have been exposed to secretarial and administrative work, finance, and innovation. I am currently pursuing a formal qualification in Innovation Management to sharpen my skill set and to better serve the youth to realise their potential and growth in their professional lives. I find great pleasure in championing initiatives directed at empowering the young and youth as I find it fulfilling to see how our future leaders grow beyond imaginable grounds. I equally strive to be an agent of positive change. My motto is: The sky is certainly not the limit and there is no harm in taking a few people along the ride with you….",
    ],
    email: "sarah@tvh.co.za",
    linkedin: "https://linkedin.com/in/sarahjohnson",
    twitter: "https://twitter.com/sarahjohnson",
    website: "https://sarahjohnson.com",
    location: "Cape Town, South Africa",
    skills: [
      "Leadership",
      "Strategic Planning",
      "Public Speaking",
      "Fundraising",
      "Community Building",
    ],
  },
  {
    id: "member-2",
    name: "Quintin Magaseng",
    title: "Chief Executive",
    department: "Executive Organizing Team",
    image: "/assets/img/team/quintin.webp",
    bio: [
      "Quintin Malope Magaseng is a passionate lecturer, who began his academic journey as a tutor, leading to lecturing roles at Eduvos, Capricorn TVET College, and currently Tshwane University of Technology (TUT) as a Lecturer and Module Coordinator in the ICT: 1st Year and Foundation Unit.\nBeyond academia, he serves as the Chief Organizer in the TVH structure, driving innovation, talent development, and industry exposure for students. He holds multiple qualifications from TUT, including a National Diploma in IT: Software Development, BTech in IT Support Services, PGDip in IT, and a PGCE from UNISA to refine his lecturing and pedagogical skills. Currently, he is completing his master’s research on Gateway Placement in Wireless Mesh Networks.\nQuintin has also earned six international certifications from Cisco and Microsoft and has held key leadership roles within TVH structure as the university-industry relations officer and the Lead Team for Digital Academy. His dedication to education, research, advancing technology and industry collaboration continues to shape the future of ICT and empower students for success.",
    ],
    email: "david@tvh.co.za",
    linkedin: "https://linkedin.com/in/davidnkosi",
    location: "Johannesburg, South Africa",
    skills: [
      "Event Management",
      "Operations",
      "Team Leadership",
      "Budget Management",
      "Strategic Planning",
    ],
  },
  {
    id: "member-3",
    name: "Dibuseng Modise",
    title: "2nd Vice Chief Organizer",
    department: "Executive Organizing Team",
    image: "/assets/img/team/modise.webp",
    bio: [
      "Priya leads TVH's partnerships and sponsorship efforts, building relationships with companies, universities, and organizations that support the hackathon's mission. She joined the leadership team in 2021 after successfully securing major sponsorships as a volunteer.",
      "With a background in marketing and business development, Priya has helped TVH establish partnerships with some of South Africa's leading tech companies and educational institutions. Her strategic approach to partnership development has been instrumental in expanding the resources and opportunities available to hackathon participants.",
      "Priya holds a Bachelor's degree in Marketing from Stellenbosch University and previously worked in corporate partnerships at a major tech accelerator.",
    ],
    email: "priya@tvh.co.za",
    linkedin: "https://linkedin.com/in/priyapatel",
    twitter: "https://twitter.com/priyapatel",
    location: "Durban, South Africa",
    skills: [
      "Partnership Development",
      "Negotiation",
      "Relationship Management",
      "Strategic Marketing",
      "Fundraising",
    ],
  },

  // Operations Team
  {
    id: "member-4",
    name: "Nkulumo Nkuna",
    title: "Infrustructure & Safety",
    department: "Executive Committee Team",
    image: "/assets/img/team/nkuna.webp",
    bio: [
      "I'm a passionate and results-oriented IT professional with over 5 years of experience across a variety of technical roles. I hold a Post Graduate Diploma (Honours degree) in Information Technology and bring valuable experience as a Solutions Architect, Cloud Administrator, Network Engineer and IT Support & End User Computing Engineer II . My expertise includes Software, Hardware, Network Architecture, Configuration, Troubleshooting, ensuring robust and efficient IT infrastructures.",
      "I excel in designing and optimizing systems to meet organizational needs while maintaining high levels of performance and security. My hands-on experience and strategic approach make me adept at resolving complex technical issues, providing comprehensive solutions, and driving continuous improvement in IT environments. I have a strong foundation in IT concepts and principles, excellent communication and interpersonal skills ability to learn and adapt to new technologies problem-solving and analytical skills ability to work independently and as part of a team.",
      "This diverse experience allows me to approach challenges from a holistic perspective, effectively bridging the gap between technical solutions and real-world business needs. I'm a strong communicator who thrives in collaborative environments and is always eager to learn and adapt to new technologies.",
    ],
    email: "thabo@tvh.co.za",
    linkedin: "https://linkedin.com/in/thabomolefe",
    location: "Johannesburg, South Africa",
    skills: [
      "Event Planning",
      "Vendor Management",
      "Crisis Management",
      "Scheduling",
      "Budgeting",
    ],
  },
  {
    id: "member-5",
    name: "Masego Dibetle",
    title: "Media,Marketing & entertainment",
    department: "Executive Committee Team",
    image: "/assets/img/team/Masego2.webp",
    bio: [
      "Masego Prudence Dibetle is a BTech Information Technology In Business Applications Graduate, current busy and almost done with her MComp in Informatics. Individual with a passion for academics. Lecturer in the 1st Year & Foundation Unit with a focus on computing fundamentals. A two-time Cum-Laude holder. A Chancellor's award was presented to her in 2019 in recognition of her outstanding academic record. For both her NDip and Btech years, she was an ICT Top 10 Achiever at the Tshwane University of Technology. During the time when TUT and Huawei were forming a partnership, she was selected to represent TUT at Huawei's Shenzhen, China headquarters. It is her passion to ensure that gender-responsive climate education is implemented, and that everyone has access to it, so that more women and girls can participate in creating a sustainable and just future. It has been noted throughout history that a significant gender gap has persisted in all sciences, technology, engineering and mathematics (STEM) disciplines worldwide. As part of her efforts to empower women, she has been involved in the Grace Hopper Conference and the Women Techmakers Scholars Program.",
    ],
    email: "lerato@tvh.co.za",
    linkedin: "https://linkedin.com/in/leratokhumalo",
    location: "Pretoria, South Africa",
    skills: [
      "Community Management",
      "Customer Service",
      "Event Coordination",
      "Problem Solving",
      "Communication",
    ],
  },

  // Technology Team
  {
    id: "member-6",
    name: "Rhulani Salani",
    title: "Registrar",
    department: "Executive Committee Team",
    image: "/assets/img/team/salani.webp",
    bio: [
      "I am a passionate Tech trailblazer who’s currently a Master’s candidate in Informatics. My journey in tech has been shaped by hands-on experience in developing mobile and web applications. I’m also skilled in cloud computing with AWS and Microsoft Azure, with a keen interest in using technology to solve real-world problems.",
      "I am a proud Golden Key International Honour Society member, recognized for academic excellence and leadership. Over the years, I’ve been actively involved in various youth-focused initiatives, including serving as a Feenix Student Ambassador and mentoring through programs like Geekulcha VacWork. These roles have allowed me to guide and inspire young people in tech, helping them unlock opportunities through innovation and collaboration.",
      "As a strong advocate for women in STEM, I am deeply committed to developing and empowering young women to thrive in technology spaces. Through mentorship and leadership, I strive to create platforms that encourage their growth, visibility, and participation in the digital economy.",
      "In my academic role, I’ve lectured IT modules such as programming, networking, and information security. I continue to support students through the development of digital content and learning strategies.",
      "As the Registrar of the Tshwane Varsity Hackathon, I am committed to creating an organized, inclusive, and impactful experience that fosters creativity, innovation, and excellence in the tech space.",
    ],
    email: "sipho@tvh.co.za",
    linkedin: "https://linkedin.com/in/siphondlovu",
    twitter: "https://twitter.com/siphondlovu",
    website: "https://siphondlovu.com",
    location: "Johannesburg, South Africa",
    skills: [
      "Software Development",
      "Cloud Infrastructure",
      "Technical Leadership",
      "System Architecture",
      "DevOps",
    ],
  },
  {
    id: "member-7",
    name: "Glen Lehlohonolo Moepi",
    title: "Industry Support",
    department: "Executive Committee Team",
    image: "/assets/img/team/moepi1.webp",
    bio: [
      "A Doctoral Candidate, with an international track in research publications. A distinction scholar with a passion for academia in teaching and learning. He has numerous accolades under his belt throughout the 20 years of experience in the public and private sector. His qualifications overlaps from Engineering to Information Communication Technology, specializing in computer architecture, networks and security. He is also SHE, CCNA and MCSE certified.",
    ],
    email: "fatima@tvh.co.za",
    linkedin: "https://linkedin.com/in/fatimaahmed",
    twitter: "https://twitter.com/fatimaahmed",
    location: "Cape Town, South Africa",
    skills: [
      "Developer Relations",
      "Technical Writing",
      "Workshop Facilitation",
      "Community Building",
      "API Integration",
    ],
  },
  {
    id: "member-8",
    name: "Elesa Ntuli",
    title: "Digital Academy",
    department: "Executive Committee Team",
    image: "/assets/img/team/mt2.webp",
    bio: [
      "Elesa Ntuli started her journey as a student assistant in TUT eMalahleni campus in 2004 while graduating her diploma in IT, currently she is a Lecturer in TUT Soshanguve from 2012 to date. She graduated from TUT and obtained her master’s degree in computer science engineering during 2013-2017, she obtained second position in ICT faculty Research Day 2015 she has few publications under her name, presently pursuing her PhD degree in Computer Science Engineering. Her research interests include Wireless Computing and Networking, TV white space, she enjoys learning and imparting knowledge to others. Amongst her degrees she obtained the following qualifications: CCNA 1,2 and 3 Certificate in A+ Support Technician National Certificate in Information Technology: System Support Project Management certificate NQF level 4 Certificate in Health and Safety Representative Construction Contractor NQF Level 2 (EPWP) Certificate in Licence to Supervise Certificate in Presenting & Publishing R&I Outcomes [Part I & II], Academic Writing On top of all this she’s a mother of 4 and a wife for 17 years and enjoys cooking.",
    ],
    email: "michael@tvh.co.za",
    linkedin: "https://linkedin.com/in/michaelvandermerwe",
    location: "Johannesburg, South Africa",
    skills: [
      "Network Engineering",
      "Cloud Infrastructure",
      "IT Support",
      "System Administration",
      "Troubleshooting",
    ],
  },

  // Organizing Team
  {
    id: "member-9",
    name: "Pearlsy Phoku",
    title: "Admin",
    department: "Organizing Team",
    image: "/assets/img/team/pearlsy.webp",
    bio: [
      "Pearlsy is an Admin in TVH structure, Has a Postgraduate Diploma in Administrative Information Management and currently in pursuit of a Masters Degree in Organisational Leadership. Her aim is to optimize the workflows and operational effeciency in TVH success.",
    ],
    email: "zoe@tvh.co.za",
    linkedin: "https://linkedin.com/in/zoemokoena",
    twitter: "https://twitter.com/zoemokoena",
    website: "https://zoemokoena.com",
    location: "Cape Town, South Africa",
    skills: [],
  },
  {
    id: "member-10",
    name: "Refiloe Mthethwa",
    title: "Digitals:Web & Online Presence",
    department: "Organizing Team",
    image: "/assets/img/team/Mthethwa.webp",
    bio: [
      "Refiloe Mthethwa, a dedicated and proactive student leader at Tshwane University of Technology's Soshanguve South Campus, is currently pursuing a diploma in informatics. With an unwavering passion for harnessing the potential of technology to foster positive change. She has played integral roles in:",
      "• Former HC Informatics Chairperson 2021/22\n• Former ICT SFC Secretary 2022/23\n• Former CSRC Deputy Secretary 2023/24",
      "Currently working under the ICT Marketing Department and Girls In Tech Ambassador.",
    ],
    email: "jamal@tvh.co.za",
    linkedin: "https://linkedin.com/in/jamalibrahim",
    website: "https://jamalibrahim.com",
    location: "Cape Town, South Africa",
    skills: [
      "UI Design",
      "UX Research",
      "Prototyping",
      "Interaction Design",
      "Front-end Development",
    ],
  },
  {
    id: "member-11",
    name: "Sibongile Malinga",
    title: "Incubation & commissioning",
    department: "Organizing Team",
    image: "/assets/img/team/sibongile.webp",
    bio: [
      "Sibongle Malinga, completed National Diploma and B-tech in Software Development, she is a lecturer at the Faculty of Information and Communications Technology, in First Year and Foundation Unit, at Tshwane University of Technology. She lecturing programming language. She is currently doing a Post graduate",
    ],
    email: "nomsa@tvh.co.za",
    linkedin: "https://linkedin.com/in/nomsadlamini",
    twitter: "https://twitter.com/nomsadlamini",
    location: "Johannesburg, South Africa",
    skills: [
      "Digital Marketing",
      "Social Media Strategy",
      "Content Creation",
      "Campaign Management",
      "Analytics",
    ],
  },
  {
    id: "member-12",
    name: "Sibongile Mthimkhulu",
    title: "Volunteers & Sponsorship",
    department: "Organizing Team",
    image: "/assets/img/team/Mthimkhulu.webp",
    bio: [
      "Education and Career: Sibongile Mthimkhulu, a trailblazer in the field of education, has recently achieved a significant milestone by completing her Master's degree in Education. Her story is one of perseverance, dedication, and a relentless commitment to transforming the lives of others through the power of learning.",
      "Early Life: Born and raised in the vibrant city of Johannesburg, South Africa, Sibongile's passion for education was ignited at a young age. Growing up in a community where access to quality schooling was limited, she witnessed firsthand the disparities that existed within the education system. Determined to make a difference, Sibongile embarked on a journey to challenge the status quo and advocate for educational equity.",
      "Conclusion: As we reflect on the remarkable achievements of Sibongile Mthimkhulu, we are reminded of the transformative power of education to break down barriers and create opportunities for all. Her journey exemplifies the values of resilience, determination, and compassion, inspiring others to dream big and pursue their passions with unwavering resolve. Sibongile's impact will continue to be felt far and wide, shaping the future of education and leaving a lasting legacy of positive change.",
    ],
    email: "alex@tvh.co.za",
    linkedin: "https://linkedin.com/in/alexchen",
    twitter: "https://twitter.com/alexchen",
    website: "https://alexchen.com",
    location: "Cape Town, South Africa",
    skills: [
      "Content Writing",
      "Video Production",
      "Social Media Content",
      "Storytelling",
      "Photography",
    ],
  },
  {
    id: "member-13",
    name: "Siviwe Binqela",
    title: "Prices, Gifts & Guest List",
    department: "Organizing Team",
    image: "/assets/img/team/siviwe.webp",
    bio: [
      "Siviwe Binqela, passionate about self-improvement, learning and sharing knowledge. A BTech graduate in the field of Information Technology (Informatics) and currently enrolled on my Post Graduate studies in the same field. I have served as an Academic Tutor in the First Year & Foundation Unit for 2years, and are now a Lecturer in the Unit with the focus on Programming and Computational Mathematics.",
    ],
    email: "olivia@tvh.co.za",
    linkedin: "https://linkedin.com/in/oliviabotha",
    location: "Johannesburg, South Africa",
    skills: [
      "Sponsorship Development",
      "Relationship Management",
      "Negotiation",
      "Proposal Writing",
      "Fundraising",
    ],
  },

  {
    id: "member-14",
    name: "Tebogo Sako",
    title: "MC's, Announcements & Presentation",
    department: "Organizing Team",
    image: "/assets/img/team/sako.webp",
    bio: [
      "Experienced radio presenter, speaker, and event host with a tech background. Skilled at sharing engaging stories and connecting with audiences. Provides fun and informative content for radio and events.",
    ],
    email: "emmanuel@tvh.co.za",
    linkedin: "https://linkedin.com/in/emmanuelokafor",
    location: "Johannesburg, South Africa",
    skills: [
      "Event Logistics",
      "Vendor Management",
      "Inventory Control",
      "Transportation Coordination",
      "Risk Management",
    ],
  },

  {
    id: "member-15",
    name: "Masedi Matlala",
    title: "Cyber-Security",
    department: "Organizing Team",
    image: "/assets/img/team/matlala.webp",
    bio: [
      "Mr. Masedi Mankwenkwe Matlala is a seasoned South African professional specializing in Information and Communication Technology (ICT), project management, and entrepreneurship. With a strong foundation in ICT, he has successfully led numerous projects, demonstrating his proficiency in managing complex technological initiatives.​​",
      "Currently, Mr. Matlala serves as a part-time lecturer at the Tshwane University of Technology (TUT), where he imparts his extensive knowledge and experience to students in the Faculty of Information and Communication Technology. His role in academia reflects his unwavering commitment to education and the development of future ICT professionals.​​",
      "Beyond his academic and professional endeavors, Mr. Matlala is deeply passionate about skills transfer and capacity building. He actively engages in initiatives aimed at empowering individuals with the necessary skills to thrive in the ever-evolving technological landscape. His dedication to mentorship and knowledge sharing underscores his belief in the transformative power of education and continuous learning.",
      "As an entrepreneur, Mr. Matlala leverages his ICT and project management expertise to drive innovation and strategic growth in various ventures. His ability to integrate technical proficiency with business acumen positions him as a dynamic leader capable of navigating the complexities of the modern digital economy.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-16",
    name: "Moeketsi Kema",
    title: "Workshops & Webinar",
    department: "Organizing Team",
    image: "/assets/img/team/kema.webp",
    bio: [
      "Moeketsi Kema is a passionate tech enthusiast, student leader, and current student at Tshwane University of Technology, pursuing a qualification in Information Technology. He serves as the AWS Cloud Club Captain and is also the Chairperson of the Hacker Society, a student-driven community focused on tech empowerment, coding, and cloud innovation.",
      "Moeketsi is dedicated to helping fellow students gain real-world skills through workshops, cloud events, and mentorship opportunities. He leads with the goal of creating inclusive spaces where students can explore technology, grow their confidence, and prepare for future careers in tech.",
      "Through his leadership roles, he continues to inspire and support a culture of learning, building, and growing together.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-17",
    name: "Happy Twala",
    title: "Ms Teams, Access Control & Data",
    department: "Organizing Team",
    image: "/assets/img/team/twala.webp",
    bio: [
      "I am a master's candidate in Information Technology with a strong foundation in networking and security. A lecturer in first year and foundation unit. I am currently deepening my expertise in cloud computing and AI.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-18",
    name: "Nkosinathi Dhladla",
    title: "Adjudication",
    department: "Organizing Team",
    image: "/assets/img/team/nkosinathi.webp",
    bio: [
      "Nkosinathi Dladla is an Associate Consultant at IQbusiness with a strong background in project management, business analysis, and data processing. He holds a Postgraduate Diploma in Management from Wits Business School and a Bachelor of Arts in International Relations and Politics from the University of the Witwatersrand. Nkosinathi is known for his critical and analytical thinking skills, which enable him to solve complex problems and create long-term strategies. He has experience working on various high-impact projects, including AML and IT PMO. In addition to his professional work, Nkosinathi is passionate about mentoring and coaching, particularly in supporting and preparing young talent for the workplace.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-19",
    name: "Phenyo Matabane",
    title: "University & Industry Relations",
    department: "Organizing Team",
    image: "/assets/img/team/Phenyo.webp",
    bio: [
      "Phenyo is an Associate Multi-Disciplinary Consultant at IQbusiness with a rich background in both the higher education and financial services sectors. His expertise spans market and economic research, community engagement, and effective project delivery. Phenyo’s attention to detail, analytical skills, and commitment to task completion make him a valuable asset in any professional setting.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-20",
    name: "Pracious Mahlangu",
    title: "Systems & Compliance",
    department: "Organizing Team",
    image: "/assets/img/team/mahlangu.webp",
    bio: [
      "Precious Mahlangu is a highly skilled and dedicated Senior Test Engineer with over five years of experience in software testing. She recently joined Discovery Limited, where she plays a pivotal role in ensuring the delivery of high-quality software solutions. Her expertise spans manual, automated, and performance testing, leveraging tools such as Selenium, Robot Framework, JIRA, Linear, Postman, JMeter, and Agile methodologies, among others.",
      "Precious is a product of ICEP and an alumna of the Tshwane University of Technology (TUT), holding a Diploma in Informatics, an Advanced Diploma in Informatics (Cum Laude), and a Postgraduate Diploma in Informatics (Cum Laude). She is currently pursuing her Master’s in Computing, demonstrating her commitment to continuous learning and professional growth.",
      "Beyond her technical expertise, Precious is known for her collaborative spirit, problem-solving abilities, and passion for innovation. She is also the Founder and CEO of Tech Gigante, an emerging IT company providing cutting-edge technology solutions and services.",
      "Her dedication to excellence and innovation continues to drive her success in the ever-evolving field of software engineering.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-21",
    name: "Dipono Manasoe",
    title: "DevOps",
    department: "Organizing Team",
    image: "/assets/img/team/dipono.webp",
    bio: [
      "I am an experienced and growth-driven IT professional currently serving as a Tech Lead at the Informatics Community Engagement Programme (ICEP), a transformative initiative under the Tshwane University of Technology’s Faculty of ICT. My journey at ICEP began as a developer, where I honed my technical skills and contributed to community-centered digital solutions. Over the years, I advanced into a leadership role, guiding teams in delivering high-impact software using the Agile Scrum framework.",
      "I hold an AWS Certified Cloud Practitioner certification, which underpins my expertise in cloud-based solutions and infrastructure optimization. My work is centered around bridging academic knowledge with real-world application, especially in underserved communities.",
      "In parallel, I play a key role in the Tshwane Varsity Hackathon (TVH) initiative, where I began as a System Compliance and DevOps specialist. I now lead as the Head of Infrastructure, overseeing cloud architecture, system integration, and ensuring scalable environments for innovative student-led projects. My contributions support the hackathon’s mission of driving the Fourth Industrial Revolution (4IR) through education, innovation, and cross-university collaboration.",
      "With a solid foundation in development, cloud technologies, and DevOps, I’m passionate about mentoring the next generation of tech talent and delivering solutions that create real social impact.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-22",
    name: "Matthews Mfati",
    title: "Logistics:Distribution & Tracking",
    department: "Organizing Team",
    image: "/assets/img/team/matthews_1.webp",
    bio: [
      "A Postgraduate student at TUT FoICT, First Years & Foundation Unit Programming Lecturer. TUT 2018 and 2019 Kasi Hackathon Lead Team",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-23",
    name: "Ayub",
    title: "AWS",
    department: "Organizing Team",
    image: "/assets/img/team/ayu.webp",
    bio: [
      "Yasser is a lecturer at Tshwane University of Technology armed with teaching experience, knowledge management systems, communication networks and software engineering. During his journey, he learned several programming styles and solutions that he still implements to this day. He has been escalating what is achievable with code to make our daily life more efficient.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-24",
    name: "Taurai Hungwe",
    title: "Sefako Makgatho Health Sciences University (SMU)",
    department: "Partners",
    image: "/assets/img/team/taurai.webp",
    bio: [
      "TAURAI HUNGWE received a PhD degree in science from Sefako Makgatho Health Sciences University (SMU), Pretoria, South Africa. He is currently a Senior Lecturer in the Department of Computer Science and Information Technology at SMU and Acting Centre Manager at SMU Centre for Entrepreneurship Rapid Incubator (CfERI). His research interests include cybersecurity, information security and digital forensics in the Cloud and databases, artificial intelligence, curriculum, teaching and learning and entrepreneurship.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-25",
    name: "Tumelo Rasedile",
    title: "Intergrated Communication Design - Faculty of Arts and Design(TUT)",
    department: "Partners",
    image: "/assets/img/team/Tumelo.webp",
    bio: [
      "Lecturer and WIL Coordinator\nIntergrated Communication Design - Faculty of Arts and Design",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Cape Town, South Africa",
    skills: [
      "Volunteer Management",
      "Training & Development",
      "Team Coordination",
      "Scheduling",
      "Community Building",
    ],
  },
  {
    id: "member-26",
    name: "Lethabo Molefe",
    title: "DevOps",
    department: "Organizing Team",
    image: "/assets/img/team/lethabo.webp",
    bio: [
      "Lethabo Tshegofatso Molefe is a DevOps enthusiast and software developer with a passion for building reliable, scalable systems that create real-world impact. He is currently pursuing an Advanced Diploma in Computer Science at Tshwane University of Technology, where he blends academic learning with practical experience in cloud infrastructure, automation, and backend development.",
      "In his role on the TVH Organising Team, Lethabo focuses on ensuring the platform runs efficiently and securely — handling tasks such as CI/CD setup, deployment automation, and system optimization. He is deeply driven by innovation and collaboration, and believes in using technology as a tool to empower and inspire.",
    ],
    email: "anele@tvh.co.za",
    linkedin: "https://linkedin.com/in/anelezwane",
    location: "Tshwane, South Africa",
    skills: [
      "Cloud Infrastructure",
      "Automation",
      "Backend Development",
      "CI/CD Pipelines",
      "Scalable Systems",
    ],
  },
];
